### ISSUE TITLE
Save grasp candidates

### ISSUE THREAD

**Issue by fbottarel** [hsp-panda/grasping-benchmarks-panda#10]
We need a way to save grasp candidates to disk, in a way that is readable to whatever needs them downstream.

@Ale909 please formalize here the syntax and the number/name of the files you require.

**Comment by Ale909** [comment]
Ok i need two files:

**generated_grasps.txt** 

in order to store the grasp candidates. In this file two generic grasp matrices  A and B  (with 4 rows and x 4 columns)  are saved in two different lines
[a11 a12 a13 a14],[a21 a22 a23 a24],[a31 a32 a33 a34],[a41 a42 a43 a44]  
[b11 b12 b13 b14],[b21 b22 b23 b24],[b31 b32 b33 b34],[b41 b42 b43 b44]  

multiple grasping poses are appended to the file

-------------------------------------------------

**generated_scores.txt**

in order to store the grasping scores.
In this file the scores are appended as below

score1
score2

**Comment by fbottarel** [comment]
@Ale909 I am assuming the matrices are stored in a row-major fashion, and the matrices are affine transformation matrices! 

Can you attach an example for each file type?

**Comment by Ale909** [comment]
yes of course, all the matrices are affine transformation matrices that are stored in a row-major 

I attached below an example for both of them
[generated_grasps.txt](https://github.com/hsp-panda/grasping-benchmarks-panda/files/6755073/generated_grasps.txt)
[generated_scores.txt](https://github.com/hsp-panda/grasping-benchmarks-panda/files/6755074/generated_scores.txt)

**Comment by fbottarel** [comment]
@Ale909 The feature has been implemented in 4a54026ca37109078d6fb3470cebb97d5b59bfd0 and will be merged soon in master.
